controllers:
    resource: ../../src/Controller/
    type: annotation

controllers_back:
    resource: ../../src/Controller/Back
    type: annotation
    prefix: /admin

controllers_front:
    resource: ../../src/Controller/Front
    type: annotation
    prefix: /

logout:
    path: /logout