version: '3.2'

services:
  db:
    image: postgres:9.6-alpine
    environment:
    - POSTGRES_DB=insider
    - POSTGRES_USER=api-platform
    - POSTGRES_PASSWORD=lmdpe
    ports:
    - "8080:5432"

volumes:
  db-data: {}